name: Build Elm
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jorelali/setup-elm@v6
        with:
          elm-version: 0.19.1
      - run: elm make
      - run: elm-test
